# Generated by Django 3.0.6 on 2020-05-31 04:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('combo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('disponibilidad', models.PositiveIntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('num_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.PositiveIntegerField(default=0, null=True)),
                ('fecha', models.PositiveIntegerField()),
                ('cliente_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('historial_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Cliente')),
                ('combo_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Combo')),
                ('entrada_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('pelicula_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sinopsis', models.TextField(max_length=100)),
                ('fecha_estreno', models.CharField(max_length=11)),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.PositiveIntegerField()),
                ('lenguaje', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('disponibilidad', models.PositiveIntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_butacas', models.PositiveIntegerField()),
                ('disponibilidad', models.PositiveIntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('Sede_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('combo_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Combo')),
                ('entrada_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Entrada')),
                ('producto_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Producto')),
                ('sala_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='historial',
            name='producto_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Producto'),
        ),
        migrations.AddField(
            model_name='historial',
            name='sede_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Sede'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='pelicula_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Pelicula'),
        ),
    ]
