# Generated by Django 3.0.6 on 2020-07-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_producto',
            fields=[
                ('num_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('num_factura', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Factura')),
                ('product_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Producto')),
            ],
        ),
    ]
