# Generated by Django 3.0.6 on 2020-07-12 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200712_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 12, 11, 21, 4, 302906)),
        ),
    ]
