# Generated by Django 3.0.6 on 2020-07-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200710_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
