# Generated by Django 3.0.6 on 2020-06-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200531_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='Sede_id',
            new_name='sede_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.PositiveIntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(),
        ),
    ]
