# Generated by Django 3.0.6 on 2020-07-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200712_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
