# Generated by Django 3.0.6 on 2020-06-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200609_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='lenguaje',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Ingles')], max_length=2),
        ),
    ]
