# Generated by Django 3.0.6 on 2020-07-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200712_1228'),
        ('api', '0004_auto_20200712_1126'),
    ]

    operations = [
    ]
