# Generated by Django 3.0.6 on 2020-06-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200618_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='genero',
        ),
    ]
