# Generated by Django 3.0.6 on 2020-06-18 22:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_pelicula_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ES', 'Español'), ('EN', 'Ingles')], max_length=5, null=True),
        ),
    ]
