# Generated by Django 3.0.6 on 2020-06-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pelicula_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='combo_id',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='entrada_id',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='sede_id',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='combo_id',
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
