# Generated by Django 3.0.6 on 2020-06-19 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200618_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='pelicula_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='entrada',
            name='ent_compradas',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='horario',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='met_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('DE', 'Debito'), ('CR', 'Credito')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='pelicula',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='sala',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='estatus',
            field=models.CharField(choices=[('PE', 'Por Estrenar'), ('EC', 'En Cartelera'), ('AR', 'Archivada')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('DU', 'Dulce'), ('SA', 'Salado')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id_funcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('pelicula_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Pelicula')),
                ('sala_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Sala')),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='funcion_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Funcion'),
        ),
    ]
