# Generated by Django 3.0.6 on 2020-06-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200619_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='entrada_id',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='sala',
            name='sede_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Sede'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='sala_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Sala'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('num_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('met_pago', models.CharField(choices=[('EF', 'Efectivo'), ('DE', 'Debito'), ('CR', 'Credito')], max_length=2, null=True)),
                ('cliente_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Cliente')),
                ('sede_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Sede')),
            ],
        ),
    ]
