# Generated by Django 3.0.6 on 2020-06-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200619_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='producto_id',
            field=models.ForeignKey(default=1, limit_choices_to=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Producto'),
        ),
    ]
