# Generated by Django 3.0.6 on 2020-06-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_factura_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='producto_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Producto'),
        ),
    ]
