# Generated by Django 3.0.6 on 2020-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200621_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='factura',
            name='producto_id',
            field=models.ManyToManyField(to='api.Producto'),
        ),
    ]
