# Generated by Django 3.0.6 on 2020-06-22 23:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200621_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='sala_id',
        ),
        migrations.AddField(
            model_name='sede',
            name='nro_salas',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'Accion'), ('AV', 'Aventura'), ('AN', 'Animacion'), ('CO', 'Comedia'), ('DR', 'Drama'), ('DO', 'Documental'), ('HO', 'Horror'), ('SU', 'Suspenso'), ('AN', 'Animacion')], max_length=26, null=True),
        ),
    ]
