# Generated by Django 3.0.6 on 2020-07-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200622_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id_lenguaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='lenguaje',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.ManyToManyField(to='api.Genero'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='lenguaje',
            field=models.ManyToManyField(to='api.Lenguaje'),
        ),
    ]
