# Generated by Django 3.0.6 on 2020-07-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200704_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='genero',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('AC', 'Accion'), ('AV', 'Aventura'), ('AN', 'Animada')], max_length=2, null=True),
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='lenguaje',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='lenguaje',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Ingles'), ('JP', 'Japones')], max_length=2, null=True),
        ),
    ]
