# Generated by Django 3.0.6 on 2020-07-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_pelicula_fecha_estreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.CharField(max_length=100),
        ),
    ]
