# Generated by Django 3.0.6 on 2020-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200706_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('AC', 'AC'), ('AV', 'AV'), ('AN', 'AN')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='lenguaje',
            field=models.CharField(choices=[('ES', 'ES'), ('EN', 'EN'), ('JP', 'JP')], max_length=2, null=True),
        ),
    ]
