# Generated by Django 3.0.6 on 2020-07-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200706_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='estatus',
            field=models.CharField(choices=[('PE', 'PE'), ('EC', 'EC'), ('AR', 'AR')], max_length=2, null=True),
        ),
    ]
