# Generated by Django 3.0.6 on 2020-07-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_pelicula_fecha_estreno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha_estreno',
        ),
    ]
