# Generated by Django 3.0.6 on 2020-07-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_pelicula_fecha_estreno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Lenguaje',
        ),
    ]
