# Generated by Django 3.0.6 on 2020-07-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200706_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('AC', 'Accion'), ('AV', 'Aventura'), ('AN', 'Animada')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='lenguaje',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Imgles'), ('JP', 'Japones')], max_length=2, null=True),
        ),
    ]
